import { createHash } from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
// @ts-expect-error Das ausführbare Node-Modul besitzt bewusst keinen TypeScript-Buildpfad.
import { backupConfiguration, diagnosticReport, promoteRelease, resolveActiveReleaseRoot, restoreConfiguration, rollbackRelease, switchCatalog } from '../scripts/operator-lifecycle.mjs';

const roots: string[] = [];
function temporary() { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'twin-operator-')); roots.push(root); return root; }
function configuration(root: string) { return { schemaVersion: 1, activeCatalogId: 'kunde-a', catalogs: [{ id: 'kunde-a', type: 'filesystem', address: path.join(root, 'a'), expectedCustomerId: 'kunde-a', expectedProjectId: 'projekt-a' }, { id: 'kunde-b', type: 'https', address: 'https://example.invalid/katalog/', expectedCustomerId: 'kunde-b', expectedProjectId: 'projekt-b' }] }; }
function release(root: string, id: string, version: string) { const releaseRoot = path.join(root, id); fs.mkdirSync(releaseRoot, { recursive: true }); const packageFile = path.join(releaseRoot, 'package.json'); fs.writeFileSync(packageFile, JSON.stringify({ name: id, version }), 'utf8'); const digest = createHash('sha256').update(fs.readFileSync(packageFile)).digest('hex'); const manifest = path.join(releaseRoot, 'release.json'); fs.writeFileSync(manifest, JSON.stringify({ schemaVersion: 1, kind: 'universaarl-twin-release', releaseId: id, applicationVersion: version, configSchemaVersion: 1, snapshotSchemaVersion: 1, packageJsonSha256: digest }), 'utf8'); return manifest; }
afterEach(() => { for (const root of roots.splice(0)) fs.rmSync(root, { recursive: true, force: true }); });

describe('lokaler Operator-Lebenszyklus', () => {
  it('wechselt explizit zwischen Kundenkatalogen und lehnt unbekannte Ziele ab', () => { const root = temporary(); const source = configuration(root); expect(switchCatalog(source, 'kunde-b').activeCatalogId).toBe('kunde-b'); expect(() => switchCatalog(source, 'kunde-c')).toThrow(/fehlt/); });
  it('sichert und restauriert ausschließlich die Katalogkonfiguration', () => { const root = temporary(); const file = path.join(root, 'config.json'); const backup = path.join(root, 'backup.json'); fs.writeFileSync(file, JSON.stringify(configuration(root))); backupConfiguration(file, backup); const body = fs.readFileSync(backup, 'utf8'); expect(body).not.toMatch(/ticket|dokument|worklog|secret/i); fs.writeFileSync(file, '{}'); restoreConfiguration(backup, file); expect(JSON.parse(fs.readFileSync(file, 'utf8')).activeCatalogId).toBe('kunde-a'); });
  it('blockiert zusätzliche Root-, Katalog- und Sicherungsfelder', () => { const root = temporary(); const file = path.join(root, 'config.json'); const backup = path.join(root, 'backup.json'); fs.writeFileSync(file, JSON.stringify({ ...configuration(root), secret: 'nicht-erlaubt' })); expect(() => backupConfiguration(file, backup)).toThrow(/ungültig/); const withToken = configuration(root); (withToken.catalogs[0] as Record<string, unknown>).token = 'nicht-erlaubt'; fs.writeFileSync(file, JSON.stringify(withToken)); expect(() => backupConfiguration(file, backup)).toThrow(/ungültig/); fs.writeFileSync(backup, JSON.stringify({ schemaVersion: 1, kind: 'universaarl-twin-config-backup', createdAt: new Date().toISOString(), configuration: configuration(root), extra: true })); expect(() => restoreConfiguration(backup, file)).toThrow(/ungültig/); });
  it('aktiviert Releases atomar, weist Downgrades ab und rollt geprüft zurück', () => { const root = temporary(); const config = path.join(root, 'config.json'); fs.writeFileSync(config, JSON.stringify(configuration(root))); const first = release(root, 'release-a', '1.0.0'); const second = release(root, 'release-b', '1.1.0'); promoteRelease(first, { config }); promoteRelease(second, { config }); expect(resolveActiveReleaseRoot({ config })).toBe(path.dirname(second)); expect(() => promoteRelease(first, { config })).toThrow(/Downgrade/); expect(rollbackRelease({ config }).releaseId).toBe('release-a'); expect(resolveActiveReleaseRoot({ config })).toBe(path.dirname(first)); });
  it('blockiert manipulierte Releasebytes und bereinigt Diagnosen', () => { const root = temporary(); const config = path.join(root, 'config.json'); fs.writeFileSync(config, JSON.stringify(configuration(root))); const manifest = release(root, 'release-a', '1.0.0'); fs.appendFileSync(path.join(path.dirname(manifest), 'package.json'), ' '); expect(() => promoteRelease(manifest, { config })).toThrow(/Digest/); const report = diagnosticReport({ config, logText: 'Fehler unter C:\\Users\\kunde\\secret und https://intern.example/token' }); expect(report.logs).not.toContain('kunde'); expect(report.logs).not.toContain('intern.example'); expect(report.host).toBe('127.0.0.1'); });
  it('blockiert ein nach der Aktivierung verändertes Releasemanifest', () => { const root = temporary(); const config = path.join(root, 'config.json'); fs.writeFileSync(config, JSON.stringify(configuration(root))); const manifest = release(root, 'release-a', '1.0.0'); promoteRelease(manifest, { config }); fs.appendFileSync(manifest, ' '); expect(() => resolveActiveReleaseRoot({ config })).toThrow(/nicht mehr unverändert/); });
  it('blockiert einen Rollback auf nachträglich manipulierte Bytes', () => { const root = temporary(); const config = path.join(root, 'config.json'); fs.writeFileSync(config, JSON.stringify(configuration(root))); const first = release(root, 'release-a', '1.0.0'); const second = release(root, 'release-b', '1.1.0'); promoteRelease(first, { config }); promoteRelease(second, { config }); fs.appendFileSync(first, ' '); expect(() => rollbackRelease({ config })).toThrow(/nicht mehr unverändert/); expect(resolveActiveReleaseRoot({ config })).toBe(path.dirname(second)); });
});
