import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { areas, parseRoute, projectUrl, type Area } from './navigation/routes';
import type { Artifact, ProjectContext, ProjectState } from './model';
import type { PublicProject } from './projects/registry';
import './styles.css';
import './theme/responsive.css';

const labels: Record<Area, string> = { 'aktueller-stand': 'Aktueller Stand', projektverlauf: 'Projektverlauf', arbeit: 'Arbeit', planung: 'Planung', lieferung: 'Lieferung', abrechnung: 'Abrechnung', quellen: 'Quellen' };
const phaseLabels: Record<string, string> = { Strategize: 'Strategie', Initiate: 'Initiierung', Implement: 'Umsetzung', Prepare: 'Vorbereitung', Operate: 'Betrieb' };
const kindLabels: Record<string, string> = { epic: 'Epic', story: 'Story', task: 'Aufgabe', change: 'Änderung', capability: 'Fähigkeit', architecture: 'Architektur', document: 'Dokument', evidence: 'Nachweis' };
const statusLabels: Record<string, string> = { approved: 'Freigegeben', planned: 'Geplant', deferred: 'Zurückgestellt', passed: 'Bestanden', active: 'Aktiv', archived: 'Archiviert', proposed: 'Vorgeschlagen', done: 'Erledigt', backlog: 'Backlog', ready: 'Bereit', 'in progress': 'In Arbeit', 'in review': 'In Prüfung', unknown: 'Unbekannt', unbekannt: 'Unbekannt', documented: 'Dokumentiert' };
const displayStatus = (value: string) => statusLabels[value.toLowerCase()] ?? value;
const unsupported: Record<Exclude<Area, 'aktueller-stand' | 'quellen'>, { title: string; text: string }> = {
  projektverlauf: { title: 'Projektverlauf noch nicht unterstützt', text: 'Projektverlauf und historische Wiedergabe werden in diesem Stand noch nicht unterstützt.' },
  arbeit: { title: 'Arbeitsansichten noch nicht unterstützt', text: 'Jira-Tafeln, Sprints und operative Arbeitsansichten folgen in einer späteren freigegebenen Änderung.' },
  planung: { title: 'Planungsansichten noch nicht unterstützt', text: 'Gantt, Kalender und Meilensteinplanung sind in diesem Stand nicht enthalten.' },
  lieferung: { title: 'Lieferungsansichten noch nicht unterstützt', text: 'Lieferungs- und Portfolioansichten werden erst auf Basis eines freigegebenen Quellenvertrags ergänzt.' },
  abrechnung: { title: 'Abrechnung noch nicht unterstützt', text: 'Arbeitszeiten, Preise und Rechnungen sind nicht im aktuellen Quellenvertrag enthalten.' },
};
type Theme = 'system' | 'light' | 'dark';

function useTheme() {
  const [theme, setTheme] = useState<Theme>(() => { const saved = localStorage.getItem('twin-theme'); return saved === 'light' || saved === 'dark' ? saved : 'system'; });
  useEffect(() => {
    const media = matchMedia('(prefers-color-scheme: dark)');
    const apply = () => { document.documentElement.dataset.theme = theme === 'system' ? (media.matches ? 'dark' : 'light') : theme; document.documentElement.dataset.themeMode = theme; };
    apply(); media.addEventListener('change', apply); localStorage.setItem('twin-theme', theme); return () => media.removeEventListener('change', apply);
  }, [theme]);
  return [theme, setTheme] as const;
}

function App() {
  const [projects, setProjects] = useState<PublicProject[]>(); const [projectsError, setProjectsError] = useState('');
  const [route, setRoute] = useState(() => parseRoute(location.pathname, [])); const [state, setState] = useState<ProjectState>(); const [stateError, setStateError] = useState('');
  const [theme, setTheme] = useTheme(); const [moreOpen, setMoreOpen] = useState(false); const [selected, setSelected] = useState<Artifact>();
  const moreButton = useRef<HTMLButtonElement>(null);
  useEffect(() => { const controller = new AbortController(); fetch('/api/projects', { signal: controller.signal }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error('Projektliste nicht verfügbar.'); return body.projects as PublicProject[]; }).then((items) => { setProjects(items); if (location.pathname === '/' && items.length === 1) history.replaceState(null, '', projectUrl(items[0].id, 'aktueller-stand')); setRoute(parseRoute(location.pathname, items.map((item) => item.id))); }).catch((error: Error) => { if (error.name !== 'AbortError') setProjectsError(error.message); }); return () => controller.abort(); }, []);
  useEffect(() => { const pop = () => projects && setRoute(parseRoute(location.pathname, projects.map((item) => item.id))); addEventListener('popstate', pop); return () => removeEventListener('popstate', pop); }, [projects]);
  useEffect(() => { if (route.kind !== 'project') { setState(undefined); return; } const projectId = route.projectId; const controller = new AbortController(); setState(undefined); setStateError(''); setSelected(undefined); fetch(`/api/projects/${encodeURIComponent(projectId)}/state`, { signal: controller.signal }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.code === 'SOURCE_UNAVAILABLE' ? 'Die freigegebene Projektquelle ist nicht verfügbar.' : 'Projektzustand nicht verfügbar.'); return body as ProjectState; }).then((next) => { if (!controller.signal.aborted && route.kind === 'project' && route.projectId === projectId) setState(next); }).catch((error: Error) => { if (error.name !== 'AbortError') setStateError(error.message); }); return () => controller.abort(); }, [route]);
  useEffect(() => { if (matchMedia('(min-width: 721px)').matches) setMoreOpen(false); const media = matchMedia('(min-width: 721px)'); const close = () => media.matches && setMoreOpen(false); media.addEventListener('change', close); return () => media.removeEventListener('change', close); }, []);
  const navigate = (projectId: string, area: Area) => { history.pushState(null, '', projectUrl(projectId, area)); setRoute({ kind: 'project', projectId, area }); setMoreOpen(false); };
  if (projectsError) return <StatusPage title="Projektliste nicht verfügbar" text={projectsError} />;
  if (!projects) return <StatusPage title="Project Twin wird geladen" text="Die freigegebene Projektregistry wird gelesen." busy />;
  if (route.kind === 'project-not-found') return <StatusPage title="Projekt nicht gefunden" text="Für diese Projekt-ID ist keine freigegebene Quelle registriert." />;
  if (route.kind === 'area-not-found' || route.kind === 'root') return <StatusPage title="Ansicht nicht verfügbar" text="Die angeforderte Projektansicht ist nicht vorhanden." />;
  const project = projects.find((item) => item.id === route.projectId)!;
  const context: ProjectContext = { projectId: project.id, projectKey: project.key, projectName: project.name };
  return <div className="app-shell">
    <a className="skip-link" href="#main">Zum Hauptinhalt springen</a>
    <Header context={context} projects={projects} area={route.area} navigate={navigate} theme={theme} setTheme={setTheme} />
    <Sidebar context={context} active={route.area} navigate={navigate} />
    <main id="main" tabIndex={-1}><div className="page-heading"><p>{context.projectKey} / {context.projectName}</p><h1>{labels[route.area]}</h1></div>{stateError ? <StatusPage title="Quelle nicht verfügbar" text={stateError} embedded /> : !state ? <StatusPage title="Projektstand wird geladen" text="Die freigegebene Quellen-Momentaufnahme wird gelesen." busy embedded /> : route.area === 'aktueller-stand' ? <CurrentState state={state} context={context} open={setSelected} /> : route.area === 'quellen' ? <Sources state={state} context={context} /> : <Unsupported area={route.area} />}</main>
    <nav className="bottom-nav" aria-label="Mobile Hauptnavigation">{(['aktueller-stand', 'projektverlauf', 'arbeit'] as Area[]).map((area) => <button key={area} aria-current={route.area === area ? 'page' : undefined} onClick={() => navigate(context.projectId, area)}><span>{area === 'aktueller-stand' ? '◉' : area === 'projektverlauf' ? '↝' : '▦'}</span>{labels[area]}</button>)}<button ref={moreButton} aria-expanded={moreOpen} aria-controls="mobile-more" onClick={() => setMoreOpen(true)}><span>•••</span>Mehr</button></nav>
    {moreOpen && <MobileMore context={context} projects={projects} active={route.area} navigate={navigate} theme={theme} setTheme={setTheme} close={() => { setMoreOpen(false); moreButton.current?.focus(); }} />}
    {selected && <Detail artifact={selected} close={() => setSelected(undefined)} />}
  </div>;
}

function Header({ context, projects, area, navigate, theme, setTheme }: { context: ProjectContext; projects: PublicProject[]; area: Area; navigate: (id: string, area: Area) => void; theme: Theme; setTheme: (value: Theme) => void }) { return <header className="topbar"><div className="brand"><strong>UNIVERSAARL</strong><span>PROJECT TWIN</span></div><label className="project-switcher">Projekt wechseln<select aria-label="Projekt wechseln" value={context.projectId} onChange={(event) => navigate(event.target.value, area)}>{projects.map((project) => <option key={project.id} value={project.id}>{project.name} · {project.key}</option>)}</select></label><ThemeSelect theme={theme} setTheme={setTheme} /></header>; }
function Sidebar({ context, active, navigate }: { context: ProjectContext; active: Area; navigate: (id: string, area: Area) => void }) { return <aside className="sidebar"><nav aria-label="Projektbereiche">{areas.map((area) => <button key={area} aria-current={active === area ? 'page' : undefined} onClick={() => navigate(context.projectId, area)}>{labels[area]}</button>)}</nav><p>NUR LESEN · {context.projectKey}</p></aside>; }
function ThemeSelect({ theme, setTheme }: { theme: Theme; setTheme: (value: Theme) => void }) { return <label className="theme-select">Darstellung<select aria-label="Darstellung wählen" value={theme} onChange={(event) => setTheme(event.target.value as Theme)}><option value="system">System</option><option value="light">Hell</option><option value="dark">Dunkel</option></select></label>; }
function MobileMore({ context, projects, active, navigate, theme, setTheme, close }: { context: ProjectContext; projects: PublicProject[]; active: Area; navigate: (id: string, area: Area) => void; theme: Theme; setTheme: (value: Theme) => void; close: () => void }) { const dialog = useRef<HTMLDivElement>(null); useEffect(() => { const focusable = () => [...dialog.current!.querySelectorAll<HTMLElement>('button,select')]; focusable()[0]?.focus(); const key = (event: KeyboardEvent) => { if (event.key === 'Escape') close(); if (event.key === 'Tab') { const items = focusable(); const first = items[0]; const last = items.at(-1); if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } } }; addEventListener('keydown', key); return () => removeEventListener('keydown', key); }, [close]); return <div className="modal-scrim" role="presentation"><div id="mobile-more" className="more-dialog" ref={dialog} role="dialog" aria-modal="true" aria-labelledby="more-title"><header><h2 id="more-title">Weitere Bereiche</h2><button onClick={close} aria-label="Menü schließen">×</button></header><label>Projekt wechseln<select aria-label="Projekt wechseln" value={context.projectId} onChange={(event) => navigate(event.target.value, active)}>{projects.map((project) => <option key={project.id} value={project.id}>{project.name} · {project.key}</option>)}</select></label><ThemeSelect theme={theme} setTheme={setTheme} /><nav aria-label="Weitere Projektbereiche">{areas.slice(3).map((area) => <button key={area} aria-current={active === area ? 'page' : undefined} onClick={() => navigate(context.projectId, area)}>{labels[area]}</button>)}</nav></div></div>; }
function CurrentState({ state, context, open }: { state: ProjectState; context: ProjectContext; open: (artifact: Artifact) => void }) { const visible = state.artifacts.slice(0, 18); return <><section className="snapshot-intro"><div><p>MOMENTAUFNAHME</p><h2>Aktueller Projektstand</h2><p>Momentaufnahme des freigegebenen Blueprint-Stands – keine historische Wiedergabe.</p></div><dl><dt>Projekt</dt><dd>{context.projectName}</dd><dt>Projekt-Key</dt><dd>{context.projectKey}</dd><dt>Quellen-Commit</dt><dd><code>{state.source.commit}</code></dd><dt>Eingelesen</dt><dd>{new Date(state.source.readAt).toLocaleString('de-DE')}</dd></dl></section><section className="summary-grid" aria-label="Aktuelle belegte Artefakte"><div><b>{state.stats.jira}</b><span>Jira-Vorgänge</span></div><div><b>{state.stats.capabilities}</b><span>Fähigkeiten</span></div><div><b>{state.stats.changes}</b><span>OpenSpec-Änderungen</span></div><div><b>{state.stats.evidence}</b><span>Prüfnachweise</span></div></section><section className="records"><header><div><p>BELEGTE ARTEFAKTE</p><h2>Aktuelle Momentaufnahme</h2></div><span>{state.artifacts.length} Datensätze</span></header><div className="record-list">{visible.map((artifact) => <button key={`${artifact.kind}-${artifact.id}`} onClick={() => open(artifact)}><code>{artifact.id}</code><span>{artifact.title}</span><small>{displayStatus(artifact.status)} · {artifact.workstream}</small></button>)}</div>{state.artifacts.length > visible.length && <p className="honest-note">Weitere {state.artifacts.length - visible.length} belegte Datensätze sind im normalisierten Zustand vorhanden.</p>}</section><section className="evidence"><header><p>NACHWEISE</p><h2>Quellgebundene Bildnachweise</h2></header>{state.evidenceItems.length ? <div className="evidence-grid">{state.evidenceItems.slice(0, 8).map((item) => <figure key={item.id}><img src={`/api/projects/${context.projectId}/evidence/${item.id}`} alt={item.title} /><figcaption>{item.title}</figcaption></figure>)}</div> : <p>Keine sicher auflösbaren PNG-Nachweise in der Momentaufnahme.</p>}</section><section className="gaps"><header><p>BEKANNTE DATENLÜCKEN</p><h2>Fehlendes bleibt sichtbar</h2></header><ul>{state.gaps.map((gap) => <li key={gap}>{gap}</li>)}</ul></section></>; }
function Sources({ state, context }: { state: ProjectState; context: ProjectContext }) { const provenance = [...new Set(state.artifacts.map((artifact) => artifact.sourcePath))].slice(0, 12); return <section className="sources"><p>SICHERE QUELLENINFORMATION</p><h2>{context.projectName} · {context.projectKey}</h2><dl><dt>Registrierungs-ID</dt><dd>{context.projectId}</dd><dt>Registrierungsname</dt><dd>{context.projectName}</dd><dt>Projekt-Key</dt><dd>{context.projectKey}</dd><dt>Quellenzweig</dt><dd>{state.source.branch}</dd><dt>Vollständiger Commit</dt><dd><code>{state.source.commit}</code></dd><dt>Quellenstatus</dt><dd>{state.source.dirty ? 'Arbeitskopie mit Änderungen' : 'Saubere Momentaufnahme'}</dd><dt>Einlesezeit</dt><dd>{new Date(state.source.readAt).toLocaleString('de-DE')}</dd></dl><h3>Sichere repository-bezogene Provenienz</h3><ul>{provenance.map((entry) => <li key={entry}><code>{entry}</code></li>)}</ul>{state.warnings.length > 0 && <><h3>Quellenhinweise</h3><ul>{state.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul></>}</section>; }
function Unsupported({ area }: { area: Exclude<Area, 'aktueller-stand' | 'quellen'> }) { const item = unsupported[area]; return <section className="unsupported"><span aria-hidden="true">∅</span><p>NOCH NICHT UNTERSTÜTZT</p><h2>{item.title}</h2><p>{item.text}</p><small>Es werden keine Beispieldaten oder Ersatzwerte erzeugt.</small></section>; }
function Detail({ artifact, close }: { artifact: Artifact; close: () => void }) { const ref = useRef<HTMLDivElement>(null); const trigger = useRef(document.activeElement as HTMLElement | null); useEffect(() => { ref.current?.querySelector<HTMLElement>('button')?.focus(); const key = (event: KeyboardEvent) => { if (event.key === 'Escape') close(); }; addEventListener('keydown', key); return () => { removeEventListener('keydown', key); trigger.current?.focus(); }; }, [close]); return <div className="drawer-scrim" onMouseDown={(event) => event.target === event.currentTarget && close()}><div className="drawer" ref={ref} role="dialog" aria-modal="true" aria-labelledby="detail-title"><button className="drawer-close" onClick={close}>Schließen ×</button><p>{kindLabels[artifact.kind] ?? artifact.kind} · {phaseLabels[artifact.phase] ?? artifact.phase}</p><h2 id="detail-title">{artifact.id}</h2><h3>{artifact.title}</h3><dl><dt>Status</dt><dd>{displayStatus(artifact.status)}</dd><dt>Arbeitsstrom</dt><dd>{artifact.workstream}</dd><dt>Quelle</dt><dd><code>{artifact.sourcePath}</code></dd></dl><h4>Begründung</h4><p>{artifact.rationale || 'Nicht in der Quelle erfasst.'}</p></div></div>; }
function StatusPage({ title, text, busy, embedded }: { title: string; text: string; busy?: boolean; embedded?: boolean }) { return <main className={`status-page ${embedded ? 'embedded' : ''}`} aria-busy={busy || undefined}><p>{busy ? 'WIRD GELADEN' : 'NICHT VERFÜGBAR'}</p><h1>{title}</h1><span>{text}</span></main>; }
createRoot(document.getElementById('root')!).render(<App />);
